import threading
import RPi.GPIO as GPIO
import time
import pygame

GPIO.setmode(GPIO.BCM)
GPIO.setup(21, GPIO.IN)
GPIO.setup(26, GPIO.IN)
GPIO.setup(14, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(20, GPIO.OUT)

isReleased = True
musicCheck = False

pygame.init()
pygame.mixer.music.load("air.mp3")
print("sound OK!")

try:
	while True:
		GPIO.output(14, False)
	    	GPIO.output(15, False)
	    	GPIO.output(18, False)
            	GPIO.output(20, False)
	    	inputValue = GPIO.input(21)

		if (inputValue == True and isReleased == True):
			print("Press Button")
		    	print("Music Play")
		    	pygame.mixer.music.play()
		    	isReleased = False
		    	musicCheck = True

			if(musicCheck == True):
                  		GPIO.output(14, True)
                    		GPIO.output(15, True)
		    		GPIO.output(18, True)
		    		GPIO.output(20, True)
		    		time.sleep(1.5)

		    		GPIO.output(20, True)
		    		GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
				GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)

				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				time.sleep(0.01)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				time.sleep(0.01)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.9)

				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(15, True)
				time.sleep(0.01)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(15, True)
				time.sleep(0.01)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.8)

				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.9)

				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)

				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				time.sleep(0.01)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				time.sleep(0.01)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.85)

				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(15, True)
				time.sleep(0.01)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.45)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.9)

				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.85)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.01)
				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(1.25)

				GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.25)
                                GPIO.output(20, True)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(1.25)

				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
                                GPIO.output(20, True)
				time.sleep(0.4)
                                GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.25)
                                GPIO.output(20, True)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(1.25)

				GPIO.output(20, True)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.5)
                                GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(1.25)

                                GPIO.output(20, True)
                                GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.5)
                                GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(1.15)
                                GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.25)
                                GPIO.output(20, True)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(1.6)

				GPIO.output(20, True)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.5)

                                GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(1.5)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
				time.sleep(0.25)

                                GPIO.output(20, False)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, False) 
				time.sleep(1.8)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(20, False)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(1.8)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(20, False)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.4)

				GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.5)
                                GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
                                GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.5)
                                GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.4)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(20, False)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.4)

				GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(1.8)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.75)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.25)
                                GPIO.output(20, False)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, False)
                                time.sleep(0.5)
                                GPIO.output(20, False)
                                GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(0.4)

				GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(1)

				GPIO.output(20, True)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, True)
				time.sleep(1)

				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.5)
				GPIO.output(20, True)
				GPIO.output(18, True)
				GPIO.output(15, True)
				GPIO.output(14, True)
				time.sleep(0.01)
				GPIO.output(20, False)
				GPIO.output(18, False)
				GPIO.output(15, False)
				GPIO.output(14, False)
				time.sleep(0.5)

				print("End..")
				exit()

except KeyboardInterrupt:
	GPIO.cleanup()

